"use client";

import { useState } from "react";
import { Inter } from "next/font/google";

import Header from "../components/Header";
import MainIntro from "../components/MainIntro";
import { LinkContext } from "../components/Contexts";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: `Numed's blog`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [activeLink, setActiveLink] = useState<string>("The blog");
  return (
    <html lang="en">
      <body className={inter.className}>
        <LinkContext.Provider value={{ activeLink, setActiveLink }}>
          <>
            <Header />
            <MainIntro title={activeLink} />
          </>
        </LinkContext.Provider>
        {children}
      </body>
    </html>
  );
}
